layout_spectrum: 0.6344086
typography_spectrum: 1
color:
  saturation: 0.7431919
  lightness: 0.6505376
  brandStrength: 1
  rhythmicContrast: 0.7527063
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
name: Greenerinks.com
