collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7473118
  brandStrength: 0.5232975
  lightness: 0.5591398
  brandColors:
    - '#87856C'
    - '#FFFFFF'
    - '#E72849'
    - '#201F25'
    - '#CDCCC8'
  rhythmicContrast: 0.3010753
typography_spectrum: 1
layout_spectrum: 0.4802867
name: Greenerinks.com
