collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 1
color:
  saturation: 0.5394265
  brandStrength: 0.562724
  lightness: 0.6899642
  brandColors:
    - '#0D0D0D'
    - '#FFFFFF'
    - '#4F5052'
    - '#C5C4C0'
    - '#FFEB3D'
  rhythmicContrast: 0.7527063
layout_spectrum: 0.4802867
name: Greenerinks.com
